apiVersion: v1
kind: Service
metadata:
  labels:
    role: locust-master
  name: locust-master
spec:
  ports:
  - port: 8089
    targetPort: 8089
    name: ui
  - port: 5557
    name: comms-primary
  - port: 5558
    name: comms-secondary
  selector:
    role: locust-master